# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-depl
spec:
    selector:
        matchLabels:
            app: app
    template:
        metadata:
            labels:
                app: app
        spec:
            containers:
                - name: tsb-app
                  image: {{ .Values.tsbImage }}
                  resources:
                      limits:
                          memory: '512Mi'
                          cpu: '500m'
                  ports:
                      - containerPort: 8080
            imagePullSecrets:
                - name: regcred
---
# Service
apiVersion: v1
kind: Service
metadata:
    name: app-serv
spec:
    selector:
        app: app
    ports:
        - port: {{ .Values.tsbPort }}
          targetPort: 8080
