apiVersion: v1
kind: PersistentVolume
metadata:
    name: data-pv
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: {{ .Values.dataStorageCapacity }}
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: '/mnt/data'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: data-pvc
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.dataStorageCapacity }}
