apiVersion: v1
kind: Secret
metadata:
    name: mongo-secr
type: Opaque
data:
    MONGO_INITDB_ROOT_USERNAME: { { .Values.secrets.mongo.username | b64enc | quote } }
    MONGO_INITDB_ROOT_PASSWORD: { { .Values.secrets.mongo.password | b64enc | quote } }
