apiVersion: v1
kind: Secret
metadata:
    name: mysql-secr
type: Opaque
data:
    MYSQL_ROOT_PASSWORD: { { .Values.secrets.mysql.rootPassword | b64enc | quote } }
    MYSQL_USER: { { .Values.secrets.mysql.username | b64enc | quote } }
    MYSQL_PASSWORD: { { .Values.secrets.mysql.password | b64enc | quote } }
